require("colorbuddy").setup()

local Color = require('colorbuddy').Color

Color.new('rosewater', '#f5e0dc') 
Color.new('flamingo', '#f2cdcd') 
Color.new('pink', '#f5c2e7') 
Color.new('mauve', '#cba6f7') 
Color.new('red', '#f38ba8') 
Color.new('maroon', '#eba0ac') 
Color.new('peach', '#fab387') 
Color.new('yellow', '#f9e2af') 
Color.new('green', '#a6e3a1') 
Color.new('teal', '#94e2d5') 
Color.new('sky', '#89dceb') 
Color.new('sapphire', '#74c7ec') 
Color.new('blue', '#89b4fa') 
Color.new('lavender', '#b4befe') 
Color.new('text', '#cdd6f4') 
Color.new('subtext1', '#bac2de') 
Color.new('subtext0', '#a6adc8') 
Color.new('overlay2', '#9399b2') 
Color.new('overlay1', '#7f849c') 
Color.new('overlay0', '#6c7086') 
Color.new('surface2', '#585b70') 
Color.new('surface1', '#45475a') 
Color.new('surface0', '#313244') 
Color.new('base', '#1e1e2e') 
Color.new('mantle', '#181825') 
Color.new('crust', '#11111b') 
